# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

{{- if .Values.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "opendistro-certs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 6 * * 2"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "opendistro-certs.fullname" . }}
          containers:
          - name: certs
            image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
              - name: RELEASE
                value: {{ .Release.Name }}
              - name: ORGANIZATION
                value: {{ .Values.organization }}
              - name: EXPIRATION
                value: {{ .Values.expiration }}
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
          restartPolicy: Never
      backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "opendistro-certs.fullname" . }}-initial
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "opendistro-certs.fullname" . }}
      containers:
      - name: certs
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: RELEASE
            value: {{ .Release.Name }}
          - name: ORGANIZATION
            value: {{ .Values.organization }}
          - name: EXPIRATION
            value: {{ .Values.expiration }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
