{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opendistro-certs.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "opendistro-certs.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['create', 'list', 'get', 'update']
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['delete', 'list']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "opendistro-certs.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "opendistro-certs.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "opendistro-certs.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
